name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: clickapp.azurecr.io
        username: clickapp
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build image
      run: docker build -t clickapp.azurecr.io/aplikacja-do-klikania:latest .

    - name: Push image
      run: docker push clickapp.azurecr.io/aplikacja-do-klikania:latest
