name: CI/CD Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login clickapp.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build
      run: docker build -t clickapp.azurecr.io/aplikacja-do-klikania:latest .

    - name: Push
      run: docker push clickapp.azurecr.io/aplikacja-do-klikania:latest
